version: '3.7'
services:
  frontend:
    build: ./frontend
    image: pcoloc/trackerlora_front
    container_name: trackerlora_front
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - trackerlora
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.1.124:24224
networks:
    trackerlora:
